version: "2"
services:
    jira:
        environment:
            - PYTHONUNBUFFERED:1
            - JIRA_URL
            - JIRA_USER
            - JIRA_PASSWORD
        build:
            context: .
        volumes:
            - ./app:/app/
        ports:
            - 1337:1337